#!/usr/bin/env python3
"""Generate the edge Caddyfile and allowed_domains.json from state branding config.

Reads config/states/*/branding.json (37 state tenants), validates each
custom_domain, and emits:

  * deploy/caddy/Caddyfile           -- one host block per state domain + fallback
  * deploy/caddy/allowed_domains.json -- consumed by the on-demand-TLS ask shim

Output is deterministic (states sorted by tenant_state_id) so the committed
files can be drift-checked in CI with --check.

Pure stdlib. Usage:

    python3 generate_caddyfile.py            # write both files
    python3 generate_caddyfile.py --check    # verify committed files match; exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
STATES_DIR = REPO_ROOT / "config" / "states"
OUT_DIR = Path(__file__).resolve().parent
CADDYFILE_PATH = OUT_DIR / "Caddyfile"
ALLOWED_PATH = OUT_DIR / "allowed_domains.json"

# Conservative FQDN validator: labels of alnum + hyphen, TLD alpha, optional
# multi-part suffix (e.g. sos.abiastate.gov.ng). Rejects malformed entries so a
# bad branding.json can never produce an invalid Caddy site address.
DOMAIN_RE = re.compile(
    r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$"
)

GENERATED_HEADER = "# GENERATED by deploy/caddy/generate_caddyfile.py -- do not edit by hand."


def load_state_domains(states_dir: Path | None = None):
    """Return (domains, skipped) lists, sorted by tenant_state_id.

    skipped contains (tenant, domain, reason) tuples for malformed entries.
    """
    if states_dir is None:
        states_dir = STATES_DIR
    entries = []
    skipped = []
    for branding in sorted(states_dir.glob("*/branding.json")):
        tenant = branding.parent.name
        try:
            data = json.loads(branding.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            skipped.append((tenant, None, f"unreadable branding.json: {exc}"))
            continue
        domain = str(data.get("custom_domain", "")).strip().lower()
        if not domain:
            skipped.append((tenant, domain, "missing custom_domain"))
            continue
        if not DOMAIN_RE.match(domain):
            skipped.append((tenant, domain, "malformed domain"))
            continue
        entries.append((tenant, domain))
    entries.sort(key=lambda e: e[0])
    return entries, skipped


STATE_BLOCK = """\
# --- {tenant} ---
{domain} {{
	# Serve the citizen PWA (static frontend) for everything that is not API.
	encode zstd gzip

	@api path /api/*
	reverse_proxy @api apisix:9080 {{
		# Preserve the tenant Host header so APISIX routes per-state.
		header_up Host {{host}}
	}}

	reverse_proxy citizen-pwa:3000

	# WAF-lite security headers at the edge (deep WAF lives in APISIX/OpenAppSec).
	header {{
		Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
		Content-Security-Policy "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https://{domain}"
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}}

	log {{
		format json
	}}
}}

"""

FALLBACK_BLOCK = """\
# --- Fallback: on-demand TLS for additional per-state custom domains ---
# Any domain NOT listed above terminates here. Caddy only issues a certificate
# after the ask endpoint approves it; the ask shim reads allowed_domains.json
# (regenerated by the sidecar from config/states/*/branding.json).
:443 {
	tls {
		on_demand
	}
	encode zstd gzip
	respond "SOS edge: domain not provisioned" 404
	header {
		-Server
	}
	log {
		format json
	}
}
"""


def build_caddyfile(entries) -> str:
    parts = [
        GENERATED_HEADER,
        "",
        "{",
        "\t# Admin API bound to localhost only (orchestrator may disable entirely).",
        "\tadmin localhost:2019",
        "\t# Prometheus metrics: scrape :2019/metrics (servers metrics enabled).",
        "\tservers {",
        "\t\tmetrics",
        "\t}",
        "\t# On-demand TLS gate. Caddy asks this GET endpoint before issuing a",
        "\t# cert for any host in the fallback block. The control-plane verify",
        "\t# endpoint is POST (/cp/v1/domains/verify), so a shim sidecar serves",
        "\t# GET /cp/v1/domains/allowed?domain={domain} backed by the regenerated",
        "\t# allowed_domains.json file (see docs/architecture/edge-caddy.md).",
        "\ton_demand_tls {",
        "\t\task http://control-plane:8000/cp/v1/domains/allowed",
        "\t\tinterval 2m",
        "\t\tburst 5",
        "\t}",
        "\temail sre@unified-sos.gov.ng",
        "}",
    ]
    parts = ["\n".join(parts), ""]
    for tenant, domain in entries:
        parts.append(STATE_BLOCK.format(tenant=tenant, domain=domain))
    parts.append(FALLBACK_BLOCK)
    return "\n".join(parts)


def build_allowed_domains(entries) -> str:
    payload = {
        "generated_by": "deploy/caddy/generate_caddyfile.py",
        "domains": sorted(domain for _, domain in entries),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed Caddyfile/allowed_domains.json match generated output",
    )
    args = parser.parse_args(argv)

    entries, skipped = load_state_domains()
    for tenant, domain, reason in skipped:
        print(f"SKIP {tenant}: {reason} (domain={domain!r})", file=sys.stderr)
    if not entries:
        print("error: no valid state domains found", file=sys.stderr)
        return 2

    caddyfile = build_caddyfile(entries)
    allowed = build_allowed_domains(entries)

    if args.check:
        ok = True
        for path, expected in ((CADDYFILE_PATH, caddyfile), (ALLOWED_PATH, allowed)):
            if not path.exists():
                print(f"DRIFT: {path} missing", file=sys.stderr)
                ok = False
            elif path.read_text(encoding="utf-8") != expected:
                print(f"DRIFT: {path} does not match generated output", file=sys.stderr)
                ok = False
        if not ok:
            return 1
        print(f"OK: {len(entries)} state domains, committed files up to date")
        return 0

    CADDYFILE_PATH.write_text(caddyfile, encoding="utf-8")
    ALLOWED_PATH.write_text(allowed, encoding="utf-8")
    print(f"wrote {CADDYFILE_PATH} ({len(entries)} state blocks)")
    print(f"wrote {ALLOWED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
