#!/usr/bin/env python3
"""Generate edge caching/compression config for Caddy and APISIX.

Emits two committed artifacts for the citizen PWA / dispatch console edge:

  * ``deploy/tuning/caddy-edge-cache.generated.conf`` — Caddy snippet:
    ``encode zstd gzip`` (brotli-style zstd preferred, gzip fallback),
    long immutable ``Cache-Control`` for fingerprinted build assets
    (``/assets/*`` — Vite emits content-hashed filenames, so a year-long
    immutable TTL is safe), and ``Cache-Control: no-store`` for money/API
    endpoints so quotes and payment confirmations are never cached by any
    intermediary or browser.
  * ``deploy/tuning/apisix-edge-cache.generated.yaml`` — APISIX global rule
    enabling the ``gzip`` plugin (gzip_types tuned for the JSON-heavy SOS
    APIs; responses >= 1 KiB only so small 202 ACKs from the offline queue
    are not needlessly compressed) plus a response-rewrite header route that
    stamps ``Cache-Control: no-store`` on the money endpoints.

The ``Cache-Control: no-store`` list MUST stay in lockstep with the service
worker's never-cache guard in ``apps/citizen-pwa/src/sw.ts`` — payment,
ledger, wallet and billing traffic is network-only end to end.

Output is deterministic so the committed files can be drift-checked in CI
with ``--check``.

Pure stdlib. Usage:

    python3 generate_edge_cache.py            # write the generated files
    python3 generate_edge_cache.py --check    # verify committed files; exit 1 on drift
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CADDY_OUTPUT = ROOT / "caddy-edge-cache.generated.conf"
APISIX_OUTPUT = ROOT / "apisix-edge-cache.generated.yaml"

GENERATED_HEADER = (
    "# GENERATED by deploy/tuning/generate_edge_cache.py -- do not edit by hand.\n"
    "# Source of truth: cache policy documented inline below + the never-cache\n"
    "# guard in apps/citizen-pwa/src/sw.ts (keep money endpoints in sync).\n"
)

#: Path prefixes that must never be cached (money endpoints). Keep in sync
#: with the NEVER_CACHE regex in apps/citizen-pwa/src/sw.ts.
NO_STORE_PREFIXES = ("/payments/", "/ledger/", "/wallet/", "/billing/")

#: Minimum response size worth compressing (bytes).
GZIP_MIN_LENGTH = 1024


def render_caddy() -> str:
    """Caddy snippet: compression + cache headers for static vs API traffic."""
    lines = [
        GENERATED_HEADER,
        "# Import into the edge site block: `import edge-cache`",
        "(edge-cache) {",
        "\t# Brotli-class (zstd) first, gzip fallback for older clients.",
        "\tencode zstd gzip",
        "",
        "\t# Fingerprinted build assets (Vite content-hash in the filename):",
        "\t# safe to cache forever; a new deploy ships a new URL.",
        "\t@immutable path /assets/* /cesium/* /icons/*",
        "\theader @immutable Cache-Control \"public, max-age=31536000, immutable\"",
        "",
        "\t# HTML shell + manifest + service worker: revalidate every load so",
        "\t# deploys take effect immediately (the SW itself uses cache-busting).",
        "\t@shell path / /index.html /manifest.webmanifest /sw.js /registerSW.js",
        "\theader @shell Cache-Control \"no-cache\"",
        "",
        "\t# Money endpoints: never cache anywhere (mirrors the SW never-cache",
        "\t# guard). Belt-and-braces with the app's own no-store responses.",
    ]
    for prefix in NO_STORE_PREFIXES:
        lines += [
            f"\t@nostore{prefix.strip('/')} path {prefix}*",
            f"\theader @nostore{prefix.strip('/')} Cache-Control \"no-store\"",
        ]
    lines += [
        "",
        "\t# Everything else API-shaped: no-store by default; read-heavy GETs",
        "\t# may relax this per-route once a server-side TTL policy exists.",
        "\t@api path /api/* /citizen/* /transparency/*",
        "\theader @api Cache-Control \"no-store\"",
        "}",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_apisix() -> str:
    """APISIX global rule: gzip plugin + no-store headers on money endpoints."""
    lines = [
        GENERATED_HEADER,
        "global_rules:",
        "  - id: edge-compression",
        "    plugins:",
        "      # Compress JSON/text responses; skip tiny bodies (offline-queue",
        "      # 202 ACKs) where gzip overhead exceeds the savings.",
        "      gzip:",
        "        min_length: " + str(GZIP_MIN_LENGTH),
        "        comp_level: 6          # balance CPU vs ratio on 3G links",
        "        types:",
        "          - application/json",
        "          - application/javascript",
        "          - text/css",
        "          - text/html",
        "          - image/svg+xml",
        "          - application/geo+json",
        "",
        "routes:",
    ]
    for i, prefix in enumerate(NO_STORE_PREFIXES, start=1):
        route_id = "no-store-" + prefix.strip("/").replace("_", "-")
        lines += [
            f"  # Money endpoint {prefix}* — never cached (see sw.ts NEVER_CACHE).",
            f"  - id: {route_id}",
            f"    uri: {prefix}*",
            "    upstream_id: sos-platform",
            "    plugins:",
            "      response-rewrite:",
            "        headers:",
            '          set:',
            '            Cache-Control: "no-store"',
        ]
        if i < len(NO_STORE_PREFIXES):
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    artifacts = {CADDY_OUTPUT: render_caddy(), APISIX_OUTPUT: render_apisix()}
    if "--check" in argv:
        stale = [p for p, text in artifacts.items() if not p.exists() or p.read_text() != text]
        if stale:
            for p in stale:
                print(f"DRIFT: {p} is stale; run generate_edge_cache.py")
            return 1
        for p in artifacts:
            print(f"OK: {p.name} up to date")
        return 0
    for path, text in artifacts.items():
        path.write_text(text)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))


# --- pytest-style checks (mirror deploy/tuning/validate_tuning.py) ----------


def test_render_is_deterministic() -> None:
    assert render_caddy() == render_caddy()
    assert render_apisix() == render_apisix()


def test_caddy_has_compression_and_immutable_assets() -> None:
    text = render_caddy()
    assert "encode zstd gzip" in text
    assert "max-age=31536000, immutable" in text
    assert "/assets/*" in text


def test_money_endpoints_never_cached_in_both_outputs() -> None:
    caddy = render_caddy()
    apisix = render_apisix()
    for prefix in NO_STORE_PREFIXES:
        assert f"{prefix}*" in caddy
        assert f"{prefix}*" in apisix
    assert caddy.count("no-store") >= len(NO_STORE_PREFIXES)
    assert apisix.count("no-store") >= len(NO_STORE_PREFIXES)


def test_sw_never_cache_guard_covers_same_prefixes() -> None:
    sw = (ROOT.parent.parent / "apps" / "citizen-pwa" / "src" / "sw.ts").read_text()
    for name in ("payments", "ledger", "wallet", "billing"):
        assert name in sw, f"sw.ts never-cache guard missing {name!r}"


def test_committed_files_match_render() -> None:
    assert CADDY_OUTPUT.read_text() == render_caddy()
    assert APISIX_OUTPUT.read_text() == render_apisix()
