#!/usr/bin/env python3
"""Generate per-tenant APISIX rate-limit routes from state policy packs.

Reads ``config/states/*/policy-pack.json`` (37 state tenants) and emits
``deploy/tuning/apisix-routes.generated.yaml``: one APISIX route per tenant,
keyed on the ``X-Sos-Tenant-State`` header (APISIX var
``http_x_sos_tenant_state``), applying:

  * ``limit-count`` — tenant quota: default 1000 requests per 60s window
    (shared tier; dedicated tier doubles it — see the commented reference in
    deploy/tuning/apisix.yaml). ``policy: redis`` so the counter is shared
    across gateway replicas (Role A cache). Exemptions (edge POS offline-sync
    bursts, /healthz, /apisix/prometheus/metrics) are shaped, not rejected —
    they bypass these routes upstream of APISIX.
  * ``limit-req``  — leaky-bucket smoothing: default 200 req/s with burst
    100 (10% of the per-minute quota) per tenant; excess bursts are delayed,
    then rejected with 503, so a noisy tenant cannot starve neighbours
    between quota resets.

Both plugins reject with 429/503 and count under the tenant header key, so
per-tenant isolation holds even when all states share one gateway upstream.
All routes proxy to the single ``sos-platform`` upstream (the in-cluster
service fan-out behind the gateway).

Output is deterministic (tenants sorted) so the committed file can be
drift-checked in CI with ``--check``.

Pure stdlib. Usage:

    python3 generate_apisix_routes.py            # write the generated file
    python3 generate_apisix_routes.py --check    # verify committed file; exit 1 on drift
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent.parent
STATES_DIR = REPO_ROOT / "config" / "states"
OUTPUT = ROOT / "apisix-routes.generated.yaml"

GENERATED_HEADER = (
    "# GENERATED by deploy/tuning/generate_apisix_routes.py -- do not edit by hand.\n"
    "# Source of truth: config/states/*/policy-pack.json (tenant list) +\n"
    "# the rate-limit defaults documented in deploy/tuning/apisix.yaml.\n"
)

#: Per-tenant quota defaults (shared tier; dedicated tier doubles these).
DEFAULT_COUNT = 1000          # requests per window
DEFAULT_TIME_WINDOW = 60      # seconds
DEFAULT_REQ_RATE = 200        # req/s leaky-bucket rate
DEFAULT_REQ_BURST = 100       # burst allowance before delay/reject
REJECTED_CODE = 429


def load_tenants(states_dir: Path = STATES_DIR) -> list[str]:
    """Sorted tenant_state_id list from config/states/*/policy-pack.json."""
    tenants = []
    for pack in sorted(states_dir.glob("*/policy-pack.json")):
        data = json.loads(pack.read_text())
        tenant = data["tenant_state_id"]
        if tenant != pack.parent.name:
            raise ValueError(
                f"{pack}: tenant_state_id {tenant!r} != directory {pack.parent.name!r}"
            )
        tenants.append(tenant)
    if not tenants:
        raise ValueError(f"no policy packs found under {states_dir}")
    return tenants


def render(tenants: list[str]) -> str:
    lines = [
        GENERATED_HEADER,
        # One shared upstream; per-tenant isolation comes from the route
        # plugins keyed on the X-Sos-Tenant-State header.
        "upstreams:",
        "  - id: sos-platform",
        "    type: roundrobin",
        "    nodes:",
        '      "control-plane.sos-platform.svc.cluster.local:8000": 1',
        "",
        "routes:",
    ]
    for tenant in tenants:
        lines += [
            f"  # --- {tenant} ---",
            f"  - id: tenant-{tenant.replace('_', '-')}",
            "    uris:",
            "      - /*",
            "    vars:",
            '      - ["http_x_sos_tenant_state", "==", "' + tenant + '"]',
            "    upstream_id: sos-platform",
            "    plugins:",
            "      # Tenant quota (shared tier 1000/min; dedicated 2000/min).",
            "      limit-count:",
            f"        count: {DEFAULT_COUNT}",
            f"        time_window: {DEFAULT_TIME_WINDOW}",
            "        key_type: var",
            "        key: http_x_sos_tenant_state",
            f"        rejected_code: {REJECTED_CODE}",
            "        policy: redis          # shared counter across gateway replicas",
            "        redis_host: redis.sos-data.svc.cluster.local",
            "        redis_port: 6379",
            "      # Leaky-bucket smoothing per tenant (burst 10% of quota).",
            "      limit-req:",
            f"        rate: {DEFAULT_REQ_RATE}",
            f"        burst: {DEFAULT_REQ_BURST}",
            "        rejected_code: 503",
            "        key_type: var",
            "        key: http_x_sos_tenant_state",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    rendered = render(load_tenants())
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(f"DRIFT: {OUTPUT} is stale; run generate_apisix_routes.py")
            return 1
        print(f"OK: {OUTPUT.name} up to date")
        return 0
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))


# --- pytest-style checks (mirror deploy/tuning/validate_tuning.py) ----------


def test_tenant_list_is_37_states() -> None:
    tenants = load_tenants()
    assert len(tenants) == 37, f"expected 37 state policy packs, got {len(tenants)}"
    assert tenants == sorted(tenants)
    assert "lagos" in tenants and "fct" in tenants


def test_render_is_deterministic() -> None:
    tenants = load_tenants()
    assert render(tenants) == render(tenants)


def test_render_one_route_per_tenant() -> None:
    text = render(load_tenants())
    for tenant in load_tenants():
        assert f'"http_x_sos_tenant_state", "==", "{tenant}"' in text
    assert text.count("limit-count:") == 37
    assert text.count("limit-req:") == 37
    assert text.count("upstream_id: sos-platform") == 37


def test_render_defaults_and_redis_policy() -> None:
    text = render(["demo_state"])
    assert "count: 1000" in text
    assert "time_window: 60" in text
    assert "rate: 200" in text and "burst: 100" in text
    assert "policy: redis" in text
    assert "rejected_code: 429" in text
    assert 'id: tenant-demo-state' in text


def test_generated_yaml_parses_and_structure() -> None:
    import yaml  # type: ignore

    text = render(load_tenants())
    doc = yaml.safe_load(text)
    assert len(doc["upstreams"]) == 1
    assert doc["upstreams"][0]["id"] == "sos-platform"
    assert len(doc["routes"]) == 37
    for route in doc["routes"]:
        assert route["vars"] == [
            ["http_x_sos_tenant_state", "==", route["id"].removeprefix("tenant-").replace("-", "_")]
        ]
        assert route["plugins"]["limit-count"]["key"] == "http_x_sos_tenant_state"
        assert route["plugins"]["limit-req"]["key"] == "http_x_sos_tenant_state"


def test_check_mode_detects_drift(tmp_path, monkeypatch) -> None:
    gen = sys.modules[__name__]

    out = tmp_path / "apisix-routes.generated.yaml"
    monkeypatch.setattr(gen, "OUTPUT", out)
    assert gen.main(["--check"]) == 1  # missing file = drift
    assert gen.main([]) == 0
    assert gen.main(["--check"]) == 0
    out.write_text(out.read_text() + "\n# tampered\n")
    assert gen.main(["--check"]) == 1
